version: '3'

services:
  myDb:
    image: postgres
    ports:
      - '5432:5432'
    container_name: postgres
    restart: always
    volumes:
      - postgres-disk:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Riven231
      POSTGRES_DB: streaming

volumes:
  postgres-disk:
